{
 "title": "SLO",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "aggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(order_aggregator_seconds_total{}[1m]))",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "histogram",
   "type": "heatmap-new",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(order_aggregator_seconds_bucket{le!=\"+Inf\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "journey", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "published",
   "type": "heatmap-new",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(order_journey_seconds_bucket{le!=\"+Inf\",stage=\"published\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "paid",
   "type": "heatmap-new",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(order_journey_seconds_bucket{le!=\"+Inf\",stage=\"paid\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "delivered",
   "type": "heatmap-new",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(order_journey_seconds_bucket{le!=\"+Inf\",stage=\"delivered\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Current SLO - Latency < 0.5s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Order",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(    \n    sum(rate(order_publish_seconds_bucket{le=\"0.5\", status=\"ok\"}[1m]))\n    /  \n    sum(rate(order_publish_seconds_count{}[1m]))\n) * 100",
     "legendFormat": "SLO"
    }
   ]
  },
  {
   "title": "Payment",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "(    \n    sum(rate(order_payment_seconds_bucket{le=\"0.5\", status=\"ok\"}[1m]))\n    /  \n    sum(rate(order_payment_seconds_count{}[1m]))\n) * 100",
     "legendFormat": "SLO"
    }
   ]
  },
  {
   "title": "Delivery",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "(    \n    sum(rate(order_delivery_seconds_bucket{le=\"0.1\", status=\"ok\"}[1m]))\n    /  \n    sum(rate(order_delivery_seconds_count{}[1m]))\n) * 100",
     "legendFormat": "SLO"
    }
   ]
  },
  {
   "title": "order_seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(order_seconds{stage=\"published\"}[1m]))",
     "legendFormat": "paid"
    },
    {
     "expr": "sum(rate(order_seconds{stage=\"delivered\"}[1m]))",
     "legendFormat": "delivered"
    },
    {
     "expr": "sum(rate(order_seconds{stage=\"published\"}[1m]))+sum(rate(order_seconds{stage=\"paid\"}[1m]))+sum(rate(order_seconds{stage=\"delivered\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}